<?php

require_once __DIR__ . '/functions/_s.php';
require_once __DIR__ . '/functions/options/first-steps.php';
require_once __DIR__ . '/functions/options/settings.php';
require_once __DIR__ . '/functions/options/social-media.php';
require_once __DIR__ . '/functions/options/events.php';
require_once __DIR__ . '/functions/events.php';
require_once __DIR__ . '/functions/excerpts.php';
require_once __DIR__ . '/functions/admin.php';
require_once __DIR__ . '/functions/metaboxes.php';
require_once __DIR__ . '/functions/blocks.php';
require_once __DIR__ . '/functions/colors.php';
require_once __DIR__ . '/functions/update.php';
require_once __DIR__ . '/functions/widgets.php';
require_once __DIR__ . '/functions/block-patterns.php';
require_once __DIR__ . '/functions/related-posts.php';
require_once __DIR__ . '/functions/activation.php';
require_once __DIR__ . '/functions/comments.php';
require_once __DIR__ . '/functions/icalimport.php';
require_once __DIR__ . '/functions/pictureimport.php';
require_once __DIR__ . '/functions/emailscrambler.php';
require_once __DIR__ . '/functions/contact-form.php';
require_once __DIR__ . '/functions/api.php';
require_once __DIR__ . '/functions/childtheme.php';
require_once __DIR__ . '/functions/menu.php';
require_once __DIR__ . '/functions/security.php';
require_once __DIR__ . '/functions/theme.php';
require_once __DIR__ . '/functions/latest-posts.php';
